apiVersion: v1
kind: Pod
metadata:
  name: mynodeapp-manual-v2
  labels:
    creation_method: manual
    env: prod
 
spec:
  containers:
  - name: mynodeapp-container
    image: anandr72/mynodeapp
    ports: 
      - containerPort: 8080
        protocol: TCP