apiVersion: v1
kind: ReplicationController
metadata:
  name: mynodeapp-rc
spec:
  replicas: 3
  selector:
    app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp-container
        image: anandr72/mynodeapp
        ports:
        - containerPort: 80